<?php

namespace Muscobytes\Laravel\TakeadsApi;

use Illuminate\Support\ServiceProvider;

class ClientServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(): void
    {
        $this->publishes([
            __DIR__ . '/../config/takeads.php' => config_path('takeads.php'),
        ], 'config');
    }
}